name: Algolia Recrawl Example

on:
  push:
    branches: [test-co]

jobs:
  algolia_crawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1
        id: algolia_crawler
        with: # mandatory parameters
          crawler-user-id: "77adda69-9bf8-464c-8290-509ea3ccaedd"
          crawler-api-key: "2271cb8646ebe78188b96fba4008e0ad"
          algolia-app-id: "QJ2QB6FCE5"
          algolia-api-key: "636c5f8d218f77cc2f87c81fbd95a9b8"
          site-url: "https://cybozu-sd.github.io/kuc-docusaurus-v2/"
